// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/add_job": {
            "post": {
                "description": "Добавляет задачу в пул для обработки воркерами",
                "tags": [
                    "Worker"
                ],
                "summary": "Добавить задачу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Задача для обработки",
                        "name": "job",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Задача добавлена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "job is required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/add_worker": {
            "post": {
                "description": "Добавляет нового воркера в пул",
                "tags": [
                    "Worker"
                ],
                "summary": "Добавить воркера",
                "responses": {
                    "200": {
                        "description": "Воркер добавлен с уникальным ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "Проверка доступности сервера",
                "tags": [
                    "Health"
                ],
                "summary": "Пинг-сервер",
                "responses": {
                    "200": {
                        "description": "PONG",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/remove_worker": {
            "delete": {
                "description": "Удаляет одного воркера из пула",
                "tags": [
                    "Worker"
                ],
                "summary": "Удалить воркера",
                "responses": {
                    "200": {
                        "description": "Воркер удален",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Worker Pool API",
	Description:      "Пример API для управления worker-пулом.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
